apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-external-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/acidflash/kublab.git
    targetRevision: main
    path: nginx-project
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-external
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
