apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: nginx-external
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /usr/share/nginx/html
