apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: update-tunnel-config
  namespace: cronjobs
spec:
  project: default
  source:
    path: cloudflare
    repoURL: https://github.com/acidflash/kublab.git
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cronjobs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
