apiVersion: v1
kind: Secret
metadata:
  name: tunnel-secrets
  namespace: argocd
type: Opaque
data:
  API_TOKEN: RjU0Z1JpTi1hMnRlbEI1dzlOR2xnUUZPbzhmNUlxVFoxdlNHcFl0VA==
  ACCOUNT_ID: NWRiMjAxM2NmMjM4Y2M4ZWM3ZGFlM2IzZjE2M2FhMjg=
  TUNNEL_ID: MTAzYmQwMTYtYjg1Mi00NzgwLWI0NjEtNDMzYzFlYzdlYTk5
