apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-tunnel-config
  namespace: argocd
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update-tunnel
            image: curlimages/curl:latest
            command:
            - /bin/sh
            - -c
            - |
              API_TOKEN=$(cat /etc/secrets/API_TOKEN)
              ACCOUNT_ID=$(cat /etc/secrets/ACCOUNT_ID)
              TUNNEL_ID=$(cat /etc/secrets/TUNNEL_ID)
              NEW_CONFIG="$(cat /etc/tunnel-config/new_config)"
              URL="https://api.cloudflare.com/client/v4/accounts/${ACCOUNT_ID}/cfd_tunnel/${TUNNEL_ID}/configurations"

              echo "Skickar PUT-förfrågan till $URL..."
              echo "Payload: $NEW_CONFIG"

              RESPONSE=$(curl -s -o /tmp/response.json -w "%{http_code}" -X PUT "$URL" \
                -H "Authorization: Bearer $API_TOKEN" \
                -H "Content-Type: application/json" \
                -d "$NEW_CONFIG")

              if [ "$RESPONSE" -eq 200 ]; then
                  echo "Tunnelkonfigurationen har uppdaterats framgångsrikt."
              else
                  echo "Fel vid uppdatering av tunnelkonfiguration: HTTP-statuskod $RESPONSE"
                  echo "Respons från API:"
                  cat /tmp/response.json || echo "Ingen respons från API."
              fi
            volumeMounts:
            - name: tunnel-config-volume
              mountPath: /etc/tunnel-config
              readOnly: true
            - name: secrets-volume
              mountPath: /etc/secrets
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: tunnel-config-volume
            configMap:
              name: tunnel-config
          - name: secrets-volume
            secret:
              secretName: tunnel-secrets
