apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  discord-webhook-url: https://discordapp.com/api/webhooks/1323039604869431436/mI1WaEYzOJ2Bn61ww7Zs3ve_su3-9VUWF88jPbLbA6x4SlMh2vi6OaSWrFb8DlD7QG07
type: Opaque
